stages:
  - build
  - deploy

variables:
  # Define any global variables here
  DOCKER_IMAGE: m1994yazdani/main-padash-client:latest

# Build Stage
build:
  stage: build
  image: docker:27.4.1
  services:
    - docker:27.4.1
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main  # Change to your default branch

# Deploy Stage
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    # Install SSH client
    - apk update && apk add --no-cache openssh
    # Setup SSH key
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # Add VPS to known_hosts to prevent SSH prompt
    - ssh-keyscan -p $VPS_PORT $VPS_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -p $VPS_PORT $VPS_USER@$VPS_HOST "
        cd /path/to/your/app ||
        git clone https://your_gitlab_server/your_group/your_repo.git /path/to/your/app;
        cd /path/to/your/app;
        git pull origin main;
        docker-compose down;
        docker-compose up -d --build
      "
  only:
    - main  # Change to your default branch
